2023-05-12 01:05:29.375 | INFO     | ths_trader:__init__:51 - 进入同花顺__网上股票交易系统5.0
2023-05-12 01:05:29.377 | INFO     | ths_trader:__init__:54 - 交易应用已存在,准备开始交易
2023-05-12 01:05:30.164 | INFO     | __main__:buy_kzz:64 - =====================================================================================
2023-05-12 01:05:30.165 | INFO     | __main__:buy_kzz:65 - 开始买入，当前kzz实时行情信息:
Pandas(Index=3, 债券代码='110068', 债券名称='龙净转债', 涨跌幅=5.16, 最新价=158.904, 最高=163.999, 最低=148.63, 今开=150.6, 涨跌额=7.793, 换手率=19.59, 量比=3.98, 动态市盈率='-', 成交量=367492, 成交额=579290704.0, 昨日收盘=151.111, 总市值='-', 流通市值=2980986761, 行情ID='1.110068', 市场类型='沪A', 更新时间='2023-05-11 16:11:49', 最新交易日='2023-05-11')
2023-05-12 01:05:34.227 | INFO     | __main__:buy_kzz:67 - 交易完成！
2023-05-12 01:05:34.236 | INFO     | __main__:buy_kzz:71 - 通知：在[2023-05-12 01:05:30.164537]时委托下单，以市价[158.904][5.16]涨幅买入[龙净转债][110068]股票
2023-05-12 01:05:34.255 | INFO     | message:send_dingding_msg:46 - 发送钉钉消息失败,错误：Traceback (most recent call last):
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 504, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oapi.dingtalk.com', port=443): Max retries exceeded with url: /robot/send?access_token=1b692186495fed1ed460592f3412c5601bf1bc056d74cc9494b66c99fe04ef99&timestamp=1683824734236&sign=EtkUdJilCnEBKTBKYB1OUeCGdayycv74zdl8xOBKgj0%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\azuma\trade\message.py", line 40, in send_dingding_msg
    resp = requests.post(api_url,
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='oapi.dingtalk.com', port=443): Max retries exceeded with url: /robot/send?access_token=1b692186495fed1ed460592f3412c5601bf1bc056d74cc9494b66c99fe04ef99&timestamp=1683824734236&sign=EtkUdJilCnEBKTBKYB1OUeCGdayycv74zdl8xOBKgj0%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

2023-05-12 01:05:34.256 | INFO     | __main__:buy_kzz:73 - =====================================================================================
2023-05-12 01:05:36.444 | INFO     | __main__:buy_kzz:64 - =====================================================================================
2023-05-12 01:05:36.445 | INFO     | __main__:buy_kzz:65 - 开始买入，当前kzz实时行情信息:
Pandas(Index=4, 债券代码='118021', 债券名称='新致转债', 涨跌幅=4.25, 最新价=147.97, 最高=156.558, 最低=144.35, 今开=144.35, 涨跌额=6.029, 换手率=271.95, 量比=9.62, 动态市盈率='-', 成交量=1318418, 成交额=1993744586.0, 昨日收盘=141.941, 总市值='-', 流通市值=717361519, 行情ID='1.118021', 市场类型='沪A', 更新时间='2023-05-11 16:11:25', 最新交易日='2023-05-11')
2023-05-12 01:05:38.044 | ERROR    | __main__:<module>:128 - Traceback (most recent call last):
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\application.py", line 250, in __resolve_control
    ctrl = wait_until_passes(
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\timings.py", line 458, in wait_until_passes
    raise err
pywinauto.timings.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 124, in <module>
    buy_kzz(ths_trader, kzz_top[:10].copy())
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 66, in buy_kzz
    ths_trader.buy_fast(symbol)
  File "D:\code\azuma\trade\ths_trader.py", line 91, in buy_fast
    stocks_num_win.draw_outline(colour='red')
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\application.py", line 379, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\application.py", line 261, in __resolve_control
    raise e.original_exception
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\application.py", line 203, in __get_ctrl
    dialog = self.backend.generic_wrapper_class(findwindows.find_element(**criteria[0]))
  File "C:\Users\ly\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\findwindows.py", line 87, in find_element
    raise ElementNotFoundError(kwargs)
pywinauto.findwindows.ElementNotFoundError: {'title': '网上股票交易系统5.0', 'control_type': 'Window', 'backend': 'uia', 'enabled_only': False, 'visible_only': False, 'process': 17392}

