2023-05-12 00:42:36.698 | INFO     | ths_trader:__init__:51 - 进入同花顺__网上股票交易系统5.0
2023-05-12 00:42:36.700 | INFO     | ths_trader:__init__:54 - 交易应用已存在,准备开始交易
2023-05-12 00:42:37.464 | ERROR    | __main__:<module>:128 - Traceback (most recent call last):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 124, in <module>
    buy_kzz(ths_trader, kzz_top[:10].copy())
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 63, in buy_kzz
    if is_start_trade(latest_price, change, high, name, symbol, debug):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 102, in is_start_trade
    return (3.3 < change < 5.5) and (not name.startswith("N")) and (not trade_maneger.bought_set().__contains__(symbol))
TypeError: 'set' object is not callable

2023-05-12 00:42:47.627 | ERROR    | __main__:<module>:128 - Traceback (most recent call last):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 124, in <module>
    buy_kzz(ths_trader, kzz_top[:10].copy())
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 63, in buy_kzz
    if is_start_trade(latest_price, change, high, name, symbol, debug):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 102, in is_start_trade
    return (3.3 < change < 5.5) and (not name.startswith("N")) and (not trade_maneger.bought_set().__contains__(symbol))
TypeError: 'set' object is not callable

2023-05-12 00:42:57.794 | ERROR    | __main__:<module>:128 - Traceback (most recent call last):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 124, in <module>
    buy_kzz(ths_trader, kzz_top[:10].copy())
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 63, in buy_kzz
    if is_start_trade(latest_price, change, high, name, symbol, debug):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 102, in is_start_trade
    return (3.3 < change < 5.5) and (not name.startswith("N")) and (not trade_maneger.bought_set().__contains__(symbol))
TypeError: 'set' object is not callable

2023-05-12 00:43:07.961 | ERROR    | __main__:<module>:128 - Traceback (most recent call last):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 124, in <module>
    buy_kzz(ths_trader, kzz_top[:10].copy())
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 63, in buy_kzz
    if is_start_trade(latest_price, change, high, name, symbol, debug):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 102, in is_start_trade
    return (3.3 < change < 5.5) and (not name.startswith("N")) and (not trade_maneger.bought_set().__contains__(symbol))
TypeError: 'set' object is not callable

2023-05-12 00:43:18.132 | ERROR    | __main__:<module>:128 - Traceback (most recent call last):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 124, in <module>
    buy_kzz(ths_trader, kzz_top[:10].copy())
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 63, in buy_kzz
    if is_start_trade(latest_price, change, high, name, symbol, debug):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 102, in is_start_trade
    return (3.3 < change < 5.5) and (not name.startswith("N")) and (not trade_maneger.bought_set().__contains__(symbol))
TypeError: 'set' object is not callable

2023-05-12 00:43:28.290 | ERROR    | __main__:<module>:128 - Traceback (most recent call last):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 124, in <module>
    buy_kzz(ths_trader, kzz_top[:10].copy())
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 63, in buy_kzz
    if is_start_trade(latest_price, change, high, name, symbol, debug):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 102, in is_start_trade
    return (3.3 < change < 5.5) and (not name.startswith("N")) and (not trade_maneger.bought_set().__contains__(symbol))
TypeError: 'set' object is not callable

2023-05-12 00:43:38.455 | ERROR    | __main__:<module>:128 - Traceback (most recent call last):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 124, in <module>
    buy_kzz(ths_trader, kzz_top[:10].copy())
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 63, in buy_kzz
    if is_start_trade(latest_price, change, high, name, symbol, debug):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 102, in is_start_trade
    return (3.3 < change < 5.5) and (not name.startswith("N")) and (not trade_maneger.bought_set().__contains__(symbol))
TypeError: 'set' object is not callable

2023-05-12 00:43:48.621 | ERROR    | __main__:<module>:128 - Traceback (most recent call last):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 124, in <module>
    buy_kzz(ths_trader, kzz_top[:10].copy())
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 63, in buy_kzz
    if is_start_trade(latest_price, change, high, name, symbol, debug):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 102, in is_start_trade
    return (3.3 < change < 5.5) and (not name.startswith("N")) and (not trade_maneger.bought_set().__contains__(symbol))
TypeError: 'set' object is not callable

2023-05-12 00:43:58.787 | ERROR    | __main__:<module>:128 - Traceback (most recent call last):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 124, in <module>
    buy_kzz(ths_trader, kzz_top[:10].copy())
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 63, in buy_kzz
    if is_start_trade(latest_price, change, high, name, symbol, debug):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 102, in is_start_trade
    return (3.3 < change < 5.5) and (not name.startswith("N")) and (not trade_maneger.bought_set().__contains__(symbol))
TypeError: 'set' object is not callable

2023-05-12 00:44:08.958 | ERROR    | __main__:<module>:128 - Traceback (most recent call last):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 124, in <module>
    buy_kzz(ths_trader, kzz_top[:10].copy())
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 63, in buy_kzz
    if is_start_trade(latest_price, change, high, name, symbol, debug):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 102, in is_start_trade
    return (3.3 < change < 5.5) and (not name.startswith("N")) and (not trade_maneger.bought_set().__contains__(symbol))
TypeError: 'set' object is not callable

2023-05-12 00:44:19.122 | ERROR    | __main__:<module>:128 - Traceback (most recent call last):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 124, in <module>
    buy_kzz(ths_trader, kzz_top[:10].copy())
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 63, in buy_kzz
    if is_start_trade(latest_price, change, high, name, symbol, debug):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 102, in is_start_trade
    return (3.3 < change < 5.5) and (not name.startswith("N")) and (not trade_maneger.bought_set().__contains__(symbol))
TypeError: 'set' object is not callable

2023-05-12 00:44:29.295 | ERROR    | __main__:<module>:128 - Traceback (most recent call last):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 124, in <module>
    buy_kzz(ths_trader, kzz_top[:10].copy())
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 63, in buy_kzz
    if is_start_trade(latest_price, change, high, name, symbol, debug):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 102, in is_start_trade
    return (3.3 < change < 5.5) and (not name.startswith("N")) and (not trade_maneger.bought_set().__contains__(symbol))
TypeError: 'set' object is not callable

2023-05-12 00:44:39.445 | ERROR    | __main__:<module>:128 - Traceback (most recent call last):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 124, in <module>
    buy_kzz(ths_trader, kzz_top[:10].copy())
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 63, in buy_kzz
    if is_start_trade(latest_price, change, high, name, symbol, debug):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 102, in is_start_trade
    return (3.3 < change < 5.5) and (not name.startswith("N")) and (not trade_maneger.bought_set().__contains__(symbol))
TypeError: 'set' object is not callable

2023-05-12 00:44:49.618 | ERROR    | __main__:<module>:128 - Traceback (most recent call last):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 124, in <module>
    buy_kzz(ths_trader, kzz_top[:10].copy())
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 63, in buy_kzz
    if is_start_trade(latest_price, change, high, name, symbol, debug):
  File "D:\code\azuma\trade\kzz_fast_v2.py", line 102, in is_start_trade
    return (3.3 < change < 5.5) and (not name.startswith("N")) and (not trade_maneger.bought_set().__contains__(symbol))
TypeError: 'set' object is not callable

